"""Small, original content catalog used by the deterministic data generator."""

TOPICS = [
    {
        "id": "python-venvs",
        "title": "Python Virtual Environments",
        "intro": "Virtual environments keep project dependencies isolated and reproducible.",
        "actions": ["Create the environment", "Activate it", "Install dependencies"],
        "details": ["Confirm the Python version", "Keep dependency versions recorded"],
        "language": "bash",
        "code": "python -m venv .venv\nsource .venv/bin/activate",
    },
    {
        "id": "git-branches",
        "title": "Safe Git Branch Cleanup",
        "intro": "A careful cleanup process removes merged branches without losing active work.",
        "actions": ["Fetch remote state", "Review merged branches", "Delete confirmed branches"],
        "details": ["Inspect the merge history", "Preserve branches with unique commits"],
        "language": "bash",
        "code": "git fetch --prune\ngit branch --merged",
    },
    {
        "id": "sql-indexes",
        "title": "Reviewing SQL Indexes",
        "intro": "Indexes should support measured query patterns rather than assumptions.",
        "actions": ["Capture the query plan", "Identify expensive scans", "Measure the new index"],
        "details": ["Record the baseline latency", "Check write overhead after the change"],
        "language": "sql",
        "code": "EXPLAIN QUERY PLAN\nSELECT * FROM orders WHERE customer_id = 42;",
    },
    {
        "id": "docker-health",
        "title": "Docker Health Checks",
        "intro": "Health checks let an orchestrator distinguish a running process from a healthy service.",
        "actions": ["Choose a health endpoint", "Set a timeout", "Test the unhealthy path"],
        "details": ["Keep the probe inexpensive", "Allow enough startup time"],
        "language": "dockerfile",
        "code": "HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost:8080/health || exit 1",
    },
    {
        "id": "api-pagination",
        "title": "API Pagination Design",
        "intro": "Stable pagination prevents clients from skipping or repeating records as data changes.",
        "actions": ["Choose a stable sort key", "Encode the cursor", "Document the next-page contract"],
        "details": ["Reject malformed cursors", "Test inserts between page requests"],
        "language": "json",
        "code": "{\"items\": [], \"next_cursor\": \"eyJpZCI6NDJ9\"}",
    },
    {
        "id": "test-fixtures",
        "title": "Maintainable Test Fixtures",
        "intro": "Focused fixtures make tests readable without hiding important setup.",
        "actions": ["Create minimal state", "Name fixtures by behavior", "Clean up external resources"],
        "details": ["Avoid shared mutable objects", "Prefer explicit defaults"],
        "language": "python",
        "code": "@pytest.fixture\ndef customer():\n    return Customer(active=True)",
    },
    {
        "id": "accessible-forms",
        "title": "Accessible Web Forms",
        "intro": "Accessible forms connect every control with a clear label and useful error message.",
        "actions": ["Associate each label", "Describe validation errors", "Test keyboard navigation"],
        "details": ["Preserve visible focus", "Announce errors to assistive technology"],
        "language": "html",
        "code": "<label for=\"email\">Email</label>\n<input id=\"email\" name=\"email\" type=\"email\">",
    },
    {
        "id": "css-grid",
        "title": "Responsive CSS Grid",
        "intro": "A responsive grid adapts column count to available space without fragile breakpoints.",
        "actions": ["Set a minimum card width", "Allow columns to wrap", "Verify narrow layouts"],
        "details": ["Use consistent gaps", "Avoid fixed container widths"],
        "language": "css",
        "code": ".grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));\n}",
    },
    {
        "id": "async-javascript",
        "title": "Reliable Async JavaScript",
        "intro": "Explicit error handling makes asynchronous operations easier to understand and recover.",
        "actions": ["Await the operation", "Handle expected failures", "Release resources"],
        "details": ["Avoid unhandled promises", "Add context to errors"],
        "language": "javascript",
        "code": "try {\n  const data = await loadData();\n} catch (error) {\n  report(error);\n}",
    },
    {
        "id": "linux-permissions",
        "title": "Linux File Permissions",
        "intro": "Least-privilege permissions limit accidental and unauthorized file access.",
        "actions": ["Inspect the current mode", "Identify the required users", "Apply the narrowest change"],
        "details": ["Avoid world-writable files", "Verify ownership separately"],
        "language": "bash",
        "code": "stat -f '%Sp %Su %Sg' config.yaml\nchmod 640 config.yaml",
    },
    {
        "id": "data-validation",
        "title": "Input Data Validation",
        "intro": "Validation at system boundaries keeps malformed data away from core logic.",
        "actions": ["Define accepted types", "Check required fields", "Return actionable errors"],
        "details": ["Normalize only documented values", "Keep validation deterministic"],
        "language": "python",
        "code": "if not isinstance(age, int) or age < 0:\n    raise ValueError('age must be a non-negative integer')",
    },
    {
        "id": "structured-logging",
        "title": "Structured Application Logging",
        "intro": "Structured fields make logs searchable and consistent across services.",
        "actions": ["Choose stable field names", "Include request context", "Exclude secrets"],
        "details": ["Use machine-readable timestamps", "Keep severity levels consistent"],
        "language": "json",
        "code": "{\"level\":\"info\",\"event\":\"checkout_complete\",\"order_id\":\"A123\"}",
    },
    {
        "id": "cache-invalidation",
        "title": "Cache Invalidation Strategy",
        "intro": "A clear invalidation policy keeps cached data fast without making it stale indefinitely.",
        "actions": ["Define ownership", "Select an expiry policy", "Measure stale reads"],
        "details": ["Version cache keys", "Plan for partial failures"],
        "language": "python",
        "code": "cache.set(key, value, ttl=300)",
    },
    {
        "id": "feature-flags",
        "title": "Feature Flag Rollouts",
        "intro": "Feature flags separate deployment from release and make gradual rollouts possible.",
        "actions": ["Define the target cohort", "Monitor guardrail metrics", "Remove the flag afterward"],
        "details": ["Provide a kill switch", "Document the flag owner"],
        "language": "python",
        "code": "if flags.enabled('new_checkout', user_id):\n    return new_checkout()",
    },
    {
        "id": "dataset-splits",
        "title": "Machine Learning Dataset Splits",
        "intro": "A leakage-resistant split provides a more honest estimate of model generalization.",
        "actions": ["Choose the grouping key", "Freeze the evaluation set", "Audit overlap"],
        "details": ["Split before augmentation", "Record the random seed"],
        "language": "python",
        "code": "train_groups, test_groups = group_split(records, key='source_id', seed=42)",
    },
    {
        "id": "prompt-versioning",
        "title": "Prompt Versioning",
        "intro": "Versioned prompts make model behavior changes traceable and reversible.",
        "actions": ["Store prompts with code", "Record model settings", "Compare against frozen cases"],
        "details": ["Use semantic identifiers", "Preserve historical evaluations"],
        "language": "yaml",
        "code": "prompt_version: 2\ntemperature: 0\nmax_tokens: 512",
    },
    {
        "id": "cli-design",
        "title": "Command-Line Interface Design",
        "intro": "Predictable command-line tools provide clear help, stable exit codes, and useful errors.",
        "actions": ["Name arguments consistently", "Validate inputs early", "Document exit behavior"],
        "details": ["Send diagnostics to stderr", "Support a non-interactive mode"],
        "language": "bash",
        "code": "tool validate --input records.jsonl --format json",
    },
    {
        "id": "release-checklist",
        "title": "Software Release Checklist",
        "intro": "A release checklist turns recurring operational knowledge into a repeatable process.",
        "actions": ["Run the test suite", "Review migrations", "Publish release notes"],
        "details": ["Confirm rollback steps", "Monitor after deployment"],
        "language": "bash",
        "code": "pytest\npython -m build",
    },
    {
        "id": "incident-response",
        "title": "Incident Response Basics",
        "intro": "A calm incident process prioritizes user impact, communication, and safe recovery.",
        "actions": ["Confirm the impact", "Assign an incident lead", "Stabilize the service"],
        "details": ["Keep a timestamped log", "Schedule a blameless review"],
        "language": "text",
        "code": "12:05 UTC - Alert confirmed\n12:09 UTC - Mitigation started",
    },
    {
        "id": "secret-management",
        "title": "Application Secret Management",
        "intro": "Secrets should be stored outside source code and rotated through a documented process.",
        "actions": ["Use a secret store", "Limit access", "Rotate exposed credentials"],
        "details": ["Never log secret values", "Audit access regularly"],
        "language": "bash",
        "code": "export API_TOKEN_FILE=/run/secrets/api_token",
    },
]
